CREATE TABLE [dbo].[Users] (
    [Id] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    [KeycloakId] UNIQUEIDENTIFIER NULL UNIQUE,
    [Username] NVARCHAR(50) NOT NULL UNIQUE,
    [Email] NVARCHAR(100) NULL,
    [FullName] NVARCHAR(100) NULL,
    [Role] NVARCHAR(20) DEFAULT 'Staff',
    [IsActive] BIT DEFAULT 1,
    [CreatedAt] DATETIME NOT NULL DEFAULT GETDATE(),
    [CreatedBy] NVARCHAR(100) NULL,
    [UpdatedAt] DATETIME NOT NULL DEFAULT GETDATE(),
    [UpdatedBy] NVARCHAR(100) NULL
);
GO
